openapi:
  project-title: MyPIL
  project-version: v1
  project-description: User registration module
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
spring:
  application:
    name: audit-tutorial
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:audittable;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        ejb:
          interceptor:
            session_scoped: com.example.userregistration.service.MyInterceptor
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
  hikari:
    minimumIdle: 5
    maximumPoolSize: 100
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTimeout: 300000
    leakDetectionThreshold: 300000
logging:
  level:
    org.hibernate: DEBUG
    event.internal: DEBUG
